import { Inter } from 'next/font/google'
import Head from 'next/head'
import axios from 'axios'
const inter = Inter({ subsets: ['latin'] })

type Props = {
  products: any
}

export default function Home({ products }: Props) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        hello
        {JSON.stringify(products)}
      </main>
    </>
  )
}

export const getStaticProps = async (context: any) => {
  const products = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/api/products`)
  console.log(products.data);

  return {
    props: {
      products: products.data
    }
  }
}