import { Inter } from 'next/font/google'
import Head from 'next/head'
import axios from 'axios'
import { ProductType } from '../../../components/shared/ProductTypes'

const inter = Inter({ subsets: ['latin'] })

type Props = {
  product: ProductType
}

export default function Home({ product }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>{product.attributes.title}</h2>
        </div>
      </main>
    </>
  )
}

export async function getStaticPaths() {

  const products = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/api/products`)

  const paths = products.data.data.map((p: ProductType) => ({
    params: { slug: p.attributes?.slug },
    // locale: p.attributes.locale
  }))

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps = async (context: any) => {
  const product = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/api/products?filters[slug][$eq]=${context.params.slug}`
  )
  return {
    props: {
      product: product.data.data[0]
    }
  }
}